### ISSUE TITLE
Issue with the result button positioning.

### ISSUE THREAD

**Issue by ansdb** [ansdb/calculator#1]
Hi everyone

I have been struggling to extend the space of the **result button** using _grid-row_ & _grid-column_.
I used these values which seem correct logically but they don't work for me:

```
button[value="="]{
    grid-column: 4/5;
    grid-row: 5/7;
}
```

Read the [contribution guidelines](https://github.com/ansdb/calculator#contribution-guidelines) or follow the following steps for a better contribution:

- After Forking, Cloning this repo create a branch with the name of the feature (in this case: e.g _result-button_).
- Open the SCSS file and add your enhancements.
- Open a pull request and I will review it, and merge it if the problem is fixed.

**NB: Please don't make any modification to the _css_ files just _sass_ file, so you need to have sass in your computer to write sass then it will be compiled to plain css**.

Thanks in advance.

**Comment by chidinma-godwin** [comment]
Are you trying to move the button to the bottom-right of it's container?

**Comment by ansdb** [comment]
@chidinma-godwin I want it to be like this button here in this image using **grid-column** and **grid-row** property, I did that as it's explained above in the _issue_ description but it doesn't work for me, even if it seems logical.

**Do you have any idea how to fix that?**

![calculator-grid](https://user-images.githubusercontent.com/30567263/70642705-fb214380-1c3f-11ea-9997-391860987a8f.JPG)

**Comment by ansdb** [comment]
Thank you so much @chidinma-godwin for your interest fixing this issue, I just want to inform you that I found a solution which is to get rid of the `grid-gap` property because it prevents the `result button` from extending using `grid-row`.
